project:
  type: website
  output-dir: Portfolio-Website

website:
  title: "Portfolio Website"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - text: "Projects"
        menu: 
          - text: Project 1
            href: ./pages/project1.qmd
          - text: Project 2
            href: ./pages/project2.qmd

format:
  html:
    theme: flatly
    toc: true
    toc-location: left
    toc-title: "Table of Contents"



