project:
  type: website
  output-dir: Portfolio-Website

website:
  title: "Portfolio Website"
  navbar:
    left:
      - text: About Me
        href: index.qmd
      - text: Academic Projects
        href: ./pages/academic_projects.qmd
      - text: Personal Projects
        href: ./pages/personal_projects.qmd
    right:
      - icon: github
        href: https://github.com/dcorcoran7
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/david-corcoran-70677917a/
        aria-label: LinkedIn

format:
  html:
    theme: flatly



