project:
  type: website
  output-dir: Homepage

website:
  title: "David Corcoran"
  back-to-top-navigation: true
  navbar:
    title: David Corcoran
    left:
      - text: About Me
        href: index.qmd
      - text: Academic Projects
        menu:
          - text: Fall 2024 - DSAN 5000 Analyzing Features that Influence Success in the Film Industry
            href: https://corcoran.georgetown.domains/5000-Project/landing_page/landing_page.html
          - text: Fall 2024 - DSAN 5100 Analyzing Airbnb Features that Rental PRicing Decisions
            href: www.google.com
      - text: Personal Projects
        menu:
          - text: Placeholder
            href: www.google.com
      - text: Resume
        href: ./pages/resume.qmd
    right:
      - icon: github
        href: https://github.com/dcorcoran7
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/david-corcoran-70677917a/
        aria-label: LinkedIn

format:
  html:
    theme: flatly
    toc: true
    toc-location: left
    toc-title: Table of Contents
    css: ./stylesheets/styles.css



