project:
  type: website
  output-dir: Portfolio-Website

website:
  title: "Portfolio Website"
  navbar:
    left:
      - text: About Me
        href: index.qmd
      - text: Projects
        href: ./pages/project_home.qmd

format:
  html:
    theme: flatly



